const h = `Heat pumps are the most energy efficent way to heat water. They work by extracting heat from the air and transferring it to the water. Traditional gas heating systems produce one Watt of heat for every Watt of energy consumed. Heat pumps produce three to five Watts of heat for every Watt of energy consumed. They are more expensive to install than gas or electric systems, but they are cheaper to run.
Factors to consider when choosing a heat pump
Cost & Rebates
Coefficient of Performance
Tank Material
Warranty
Noise Level
User Reviews
Refrigerant & Operating Temperature Range
Most of the details are included in following table

Coefficient of Performance (COP)
Defined as the ratio of heat output to the amount of electricity used to produce the heat. The higher the COP, the more efficient the heat pump. A COP of 3 means that for every 1kW of electricity used, 3kW of heat is produced. The COP of a heat pump is affected by the temperature of the air and water. The COP is higher when the air and water are warmer. The COP is lower when the air and water are colder. The COP of a heat pump is also affected by the size of the heat pump. Larger heat pumps have higher COPs than smaller heat pumps. The COP of a heat pump is also affected by the design of the heat pump. Some heat pumps have higher COPs than others. The COP of a heat pump is also affected by the quality of the installation. A poorly installed heat pump will have a lower COP than a well installed heat pump. The COP of a heat pump is also affected by the maintenance of the heat pump. A poorly maintained heat pump will have a lower COP than a well maintained heat pump. The COP of a heat pump is also affected by the age of the heat pump. An old heat pump will have a lower COP than a new heat pump. The COP of a heat pump is also affected by the brand of the heat pump. Some brands have higher COPs than others. The COP of a heat pump is also affected by the price of the heat pump. More expensive heat pumps have higher COPs than cheaper heat pumps. The COP of a heat pump is also affected by the location of the heat pump. Heat pumps in warmer climates have higher COPs than heat pumps in colder climates. The COP of a heat pump is also affected by the type of heat pump. Some types of heat pumps have higher COPs than others. The COP of a heat pump is also affected by the size of the tank. Larger tanks have higher COPs than smaller tanks. The COP of a heat pump is also affected by the type of tank. Some types of tanks have higher COPs than others. The COP of a heat pump is also affected by the size of the compressor. Larger compressors have higher COPs than smaller compressors. The COP of a heat pump is also affected by the type of compressor. Some types of compressors have higher COPs than others. The COP of a heat pump is also affected by the size of the evaporator. Larger evaporators have higher COPs than smaller

Tank Material

Stainless Steel: Some heat pump tanks are made from stainless steel, which is known for its durability and resistance to corrosion. Stainless steel tanks do not require an internal lining to prevent rust, making them a good option for water storage. They are often used in environments where water quality can be aggressive towards less durable materials. Stainless stee is used in high-end heat pump water heaters, as it is more expensive than other materials.
Glass-Lined Steel: Another common material is glass-lined steel, which combines the strength and flexibility of steel with the corrosion resistance of glass. This is achieved by coating the interior steel surfaces with a thin layer of glass that has been fused to the steel at high temperatures. This is a good option where the water quality is poor and can cause corrosion.
Vitreous Enamel: This is a popular choice for lining the inside of heat pump water tanks. Vitreous enamel, also known as porcelain enamel, is a material made by fusing powdered glass to a substrate by firing, usually between 750 and 850 degrees Celsius. The powder melts, flows, and then hardens to a smooth, durable vitreous coating on metal, which is highly resistant to corrosion. This makes it ideal for water storage as it can protect the tank from rust and the effects of water quality.

Refrigerant & Operating Temperature Range

R134A: R134A is a hydrofluorocarbon refrigerant that is commonly used in heat pump water heaters. It has a low global warming potential (GWP) of 1,430, which means it has a lower impact on the environment than other refrigerants. R134A is non-toxic, non-flammable, and non-corrosive, making it a safe option for heat pump water heaters. It is also widely available and affordable, making it a popular choice for manufacturers. R134A has a boiling point of -26.3 degrees Celsius, which means it can operate efficiently in a wide range of temperatures. This makes it suitable for use in heat pump water heaters that are installed in a variety of climates.
CO₂: Carbon dioxide (CO₂) is a natural refrigerant that is becoming more popular in heat pump water heaters. It has a GWP of 1, which means it has no impact on the environment. CO₂ is non-toxic, non-flammable, and non-corrosive, making it a safe option for heat pump water heaters. It is also widely available and affordable, making it a popular choice for manufacturers. CO₂ has a boiling point of -78.5 degrees Celsius, which means it can operate efficiently in a wide range of temperatures. This makes it suitable for use in heat pump water heaters that are installed in a variety of climates. CO₂ is also non-ozone depleting, which means it does not contribute to the depletion of the ozone layer. This makes it a sustainable option for heat pump water heaters.
Propane: Propane (R290) is a hydrocarbon refrigerant that is commonly used in heat pump water heaters. It has a GWP of 3, which means it has a low impact on the environment. Propane is non-toxic, non-flammable, and non-corrosive, making it a safe option for heat pump water heaters. It is also widely available and affordable, making it a popular choice for manufacturers. Propane has a boiling point of -42 degrees Celsius, which means it can operate efficiently in a wide range of temperatures. This makes it suitable for use in heat pump water heaters that are installed in a variety of climates. Propane is also non-ozone depleting, which means it does not contribute to the depletion of the ozone layer. This makes it a sustainable option for heat pump water heaters.
`